[profile.default]
src = "src"
out = "out"
libs = ["lib"]
optimizer = true
optimizer-runs = 1_000
viaIR = true
gas_reports = ["*"]

[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"
basemainnet = "${BASE_MAINNET_RPC_URL}"
basesepolia = "${BASE_SEP_RPC_URL}"
optimism-sepolia = "${OP_SEPOLIA_URL}"
polygon-mumbai = "${POLYGON_MUMBAI_RPC_URL}"

[etherscan]
mainnet = { key = "${ETHERSCAN_API_KEY}", url = "https://api.etherscan.io/api" }
optimism = { key = "${ETHERSCAN_OPTIMISM_API_KEY}", url = "https://api-optimistic.etherscan.io/api" }

sepolia = { key = "${ETHERSCAN_API_KEY}", url = "https://api-sepolia.etherscan.io/api" }
optimism-sepolia = { key = "${OPTIMISM_ETHERSCAN_API_KEY}", url = "https://api-sepolia-optimistic.etherscan.io/api" }

# https://book.getfoundry.sh/cheatcodes/rpc
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
